config/routes.rb
Rails.application.routes.draw do
  # resources :timesheets
  root "timesheets#new", as: "root"
  get "/timesheets", to: "timesheets#index", as: "timesheets"
  post "/timesheets", to: "timesheets#create"
  get "/timesheets/new", to: "timesheets#new", as: "new_timesheet"
  get "/timesheet/:id/edit", to: "timesheets#edit", as: "edit_timesheet"
  get "/timesheets/:id", to: "timesheets#show", as: "timesheet"
  patch "/timesheets/:id", to: "timesheets#update"
  delete "timesheets/:id", to: "timesheets#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :set_timesheet, only: %i[ show edit update destroy ]

  # GET /timesheets or /timesheets.json
  def index
    @timesheets = Timesheet.all
  end

  # GET /timesheets/1 or /timesheets/1.json
  def show
  end

  # GET /timesheets/new
  def new
    @timesheet = Timesheet.new
  end

  # GET /timesheets/1/edit
  def edit
  end

  # POST /timesheets or /timesheets.json
  def create
    @timesheet = Timesheet.new(timesheet_params)

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to @timesheet, notice: "Timesheet was successfully created." }
        format.json { render :show, status: :created, location: @timesheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1 or /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to @timesheet, notice: "Timesheet was successfully updated." }
        format.json { render :show, status: :ok, location: @timesheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1 or /timesheets/1.json
  def destroy
    @timesheet.destroy
    respond_to do |format|
      format.html { redirect_to timesheets_url, notice: "Timesheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timesheet
      @timesheet = Timesheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def timesheet_params
      params.require(:timesheet).permit(:date, :start_time, :finish_time, :calculated_rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimesheetApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/timesheets/_form.html.erb
<%= form_with(model: timesheet) do |form| %>
  <% if timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
        <% timesheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :finish_time %>
    <%= form.time_select :finish_time %>
  </div>

  <div class="field">
    <%= form.label :calculated_rate %>
    <%= form.text_field :calculated_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h1>Editing Timesheet</h1>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timesheets</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Start time</th>
      <th>Finish time</th>
      <th>Calculated rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timesheets.each do |timesheet| %>
      <tr>
        <td><%= timesheet.date %></td>
        <td><%= timesheet.start_time %></td>
        <td><%= timesheet.finish_time %></td>
        <td><%= timesheet.calculated_rate %></td>
        <td><%= link_to 'Show', timesheet %></td>
        <td><%= link_to 'Edit', edit_timesheet_path(timesheet) %></td>
        <td><%= link_to 'Destroy', timesheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timesheet', new_timesheet_path %>

app/views/timesheets/new.html.erb
<h1>New Timesheet</h1>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Back', timesheets_path %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @timesheet.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @timesheet.start_time %>
</p>

<p>
  <strong>Finish time:</strong>
  <%= @timesheet.finish_time %>
</p>

<p>
  <strong>Calculated rate:</strong>
  <%= @timesheet.calculated_rate %>
</p>

<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>